#!/bin/sh
# More regression tests for libnuma/numa api

VALGRIND=${VALGRIND:-}

T() {
       echo "$@" 
       if ! $VALGRIND "$@" ;  then
	  echo	$1 FAILED!!!!
	  exit 1
       fi
       echo
}

# still broken
#T ./prefered
T ./distance
T ./nodemap
T ./checkaffinity
T ./checktopology
T ./tbitmap
T ./bind_range
#T ./randmap
